---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gofiggy
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gofiggy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gofiggy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gofiggy
subjects:
  - kind: ServiceAccount
    name: gofiggy
    namespace: default
