apiVersion: v1
data:
  special.how: very
  special.type: charm
  special.power: flying
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-04T10:02:30Z"
  name: special-config
  namespace: default
  resourceVersion: "4003"
  selfLink: /api/v1/namespaces/default/configmaps/special-config
  uid: 48e504a1-b8ab-4658-a2aa-f857eb39879e
